name: Docker
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/prod/web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/web:latest
